### ISSUE TITLE
Dark mode toggle bugs while changing pages

### ISSUE THREAD

**Issue by Kn99HN** [BUGS-NYU/bugs-nyu.github.io-old#172]
If the dark mode toggle state is not consistent when changing between pages. Sometimes it will be dark and toggle would be off and vice versa

**Comment by esilverm** [comment]
It looks my themeContext file is toggling the change optimistically but not updating the actual root styles until the user refreshes.

**Comment by esilverm** [comment]
I think i found the problem. I must've accidentally removed the code where we set the property `--initial-color-mode` within the [setColorMode](https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/9c163f5cde5a2e2f1c4d47dd985e9db8bc978203/src/components/themeContext.js#L17) function so that value doesn't change immediately despite the rest of the dark mode values changing. This means that we require a re-run (refresh) of the file's useEffect hook to pull the latest color mode and update that value.
